service: nuxt-serverless-container

provider:
  name: aws
  stage: stg
  region: ap-northeast-1
  environment:
    NODE_ENV: stg
  ecr:
    images:
      nuxt:
        path: .

functions:
  nuxt:
    image:
      name: nuxt
    events:
      - httpApi: '*'
